# Generated by Django 4.2.11 on 2024-04-18 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AyazMariTimeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpdata',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AyazMariTimeApp.rankmaster', verbose_name='RANK'),
        ),
    ]
