# Generated by Django 4.2.11 on 2024-04-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AyazMariTimeApp', '0002_alter_dumpdata_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dumpdata',
            name='exppay',
        ),
        migrations.RemoveField(
            model_name='dumpdata',
            name='gap',
        ),
        migrations.AddField(
            model_name='dumpdata',
            name='pay2',
            field=models.BigIntegerField(default=0, max_length=10, verbose_name='PAY 2'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AyazMariTimeApp.currencymaster', verbose_name='CURRENCY'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='pay1',
            field=models.BigIntegerField(max_length=10, verbose_name='PAY 1'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dumpdata_set', to='AyazMariTimeApp.rankmaster', verbose_name='RANK'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='rank2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dumpdata_set2', to='AyazMariTimeApp.rankmaster', verbose_name='RANK2'),
        ),
    ]
