# Generated by Django 4.2.11 on 2024-04-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AyazMariTimeApp', '0003_remove_dumpdata_exppay_remove_dumpdata_gap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpdata',
            name='pay2',
            field=models.BigIntegerField(default='', max_length=10, verbose_name='PAY 2'),
        ),
    ]
