# Generated by Django 4.2.11 on 2024-04-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AyazMariTimeApp', '0004_alter_dumpdata_pay2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpdata',
            name='pay2',
            field=models.BigIntegerField(max_length=10, verbose_name='PAY 2'),
        ),
    ]
