# Generated by Django 4.2.11 on 2024-04-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AyazMariTimeApp', '0005_alter_dumpdata_pay2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dumpdata',
            name='customid2',
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='customid',
            field=models.BigIntegerField(max_length=10, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID2'),
        ),
    ]
