# Generated by Django 4.2.11 on 2024-04-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AyazMariTimeApp', '0006_remove_dumpdata_customid2_alter_dumpdata_customid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpdata',
            name='customid',
            field=models.CharField(max_length=10, verbose_name='ID'),
        ),
    ]
