# Generated by Django 4.2.11 on 2024-04-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AyazMariTimeApp', '0007_alter_dumpdata_customid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpdata',
            name='customid',
            field=models.CharField(max_length=10, unique=True, verbose_name='ID'),
        ),
    ]
