# Generated by Django 4.2.11 on 2024-04-20 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AyazMariTimeApp', '0008_alter_dumpdata_customid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpdata',
            name='alvdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='AVL DATE'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='customid',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='mobno',
            field=models.BigIntegerField(blank=True, default='', max_length=15, unique=True, verbose_name='MOBILE NO'),
        ),
    ]
