# Generated by Django 4.2.11 on 2024-04-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AyazMariTimeApp', '0009_alter_dumpdata_alvdate_alter_dumpdata_customid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpdata',
            name='passport',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='PASSPORT'),
        ),
    ]
