# Generated by Django 4.2.11 on 2024-04-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AyazMariTimeApp', '0010_alter_dumpdata_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpdata',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, verbose_name='REMARKS'),
        ),
    ]
