# Generated by Django 4.2.11 on 2024-04-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AyazMariTimeApp', '0012_alter_dumpdata_customid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpdata',
            name='customid',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='ID'),
        ),
    ]
