# Generated by Django 4.2.11 on 2024-04-21 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AyazMariTimeApp', '0013_alter_dumpdata_customid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpdata',
            name='alvdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='AVL DATE'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='customid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='DATE OF BIRTH'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='passport',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True, verbose_name='PASSPORT'),
        ),
    ]
