# Generated by Django 4.2.11 on 2024-04-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AyazMariTimeApp', '0014_alter_dumpdata_alvdate_alter_dumpdata_customid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpdata',
            name='alvdate',
            field=models.DateField(blank=True, default='', null=True, verbose_name='AVL DATE'),
        ),
    ]
