# Generated by Django 4.2.11 on 2024-04-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AyazMariTimeApp', '0015_alter_dumpdata_alvdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpdata',
            name='pay1',
            field=models.BigIntegerField(blank=True, max_length=10, verbose_name='PAY 1'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='pay2',
            field=models.BigIntegerField(blank=True, max_length=10, verbose_name='PAY 2'),
        ),
    ]
