# Generated by Django 4.2.11 on 2024-04-27 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AyazMariTimeApp', '0016_alter_dumpdata_pay1_alter_dumpdata_pay2'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumpdata',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dumpdata',
            name='updatedate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='currency',
            field=models.ForeignKey(blank=True, default=7, null=True, on_delete=django.db.models.deletion.CASCADE, to='AyazMariTimeApp.currencymaster', verbose_name='CURRENCY'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='eng',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='AyazMariTimeApp.engmaster', verbose_name='ENG'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='flag',
            field=models.ForeignKey(default=21, null=True, on_delete=django.db.models.deletion.CASCADE, to='AyazMariTimeApp.flagmaster', verbose_name='FLAG'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='mobno',
            field=models.CharField(blank=True, default='', max_length=20, unique=True, verbose_name='MOBILE NO'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='pay',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='AyazMariTimeApp.paymaster', verbose_name='PAY'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='pump',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='AyazMariTimeApp.pumpmaster', verbose_name='PUMP'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='rank',
            field=models.ForeignKey(default=9, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dumpdata_set', to='AyazMariTimeApp.rankmaster', verbose_name='RANK'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='rank2',
            field=models.ForeignKey(default=9, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dumpdata_set2', to='AyazMariTimeApp.rankmaster', verbose_name='RANK2'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='sc',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='AyazMariTimeApp.scmaster', verbose_name='SC'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='ship2',
            field=models.ForeignKey(default=16, null=True, on_delete=django.db.models.deletion.CASCADE, to='AyazMariTimeApp.ship2master', verbose_name='SHIP2'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='visa',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='AyazMariTimeApp.visamaster', verbose_name='VISA'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='vs',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='AyazMariTimeApp.vsmaster', verbose_name='VS'),
        ),
        migrations.AlterField(
            model_name='dumpdata',
            name='vt',
            field=models.ForeignKey(default=16, null=True, on_delete=django.db.models.deletion.CASCADE, to='AyazMariTimeApp.vtmaster', verbose_name='VT'),
        ),
    ]
