# Generated by Django 4.2.11 on 2024-04-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AyazMatiTimeApp', '0002_dumpdata_delete_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpdata',
            name='mobno',
            field=models.BigIntegerField(max_length=15, verbose_name='MOBILE NO'),
        ),
    ]
